version: '2'
services:
  # Uploader API
  uploader:
    build: .
    command: puma
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "9292:9292"
    links:
      - clamav-rest
  # Virus Scanner (https://github.com/ministryofjustice/malware-scanner-service)
  clamav:
    image: registry.service.dsd.io/ministryofjustice/malware-scanner-service-clamav:v1.1.0
  clamav-rest:
    image: registry.service.dsd.io/ministryofjustice/malware-scanner-service-clamav-rest:v1.1.0
    links:
      - clamav:clamav-server
    environment:
      HOST: clamav-server
      PORT: 3310
    depends_on:
      - clamav
    ports:
      - 8080:8080
