version: '2'
services:
  # Uploader API
  uploader:
    build: .
    command: puma
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "9292:9292"
    links:
      - clamav-rest
  clamav:
    # https://github.com/ministryofjustice/moj-clamav-daemon
    image: registry.service.dsd.io/ministryofjustice/clamav:0.1.0
  clamav-rest:
    # https://github.com/ministryofjustice/moj-clamav-rest
    image: registry.service.dsd.io/ministryofjustice/clamav-rest:0.1.0
    links:
      - clamav:clamav-server
    environment:
      HOST: clamav-server
      PORT: 3310
    depends_on:
      - clamav
    ports:
      - 8080:8080
