version: '2'
services:
  # Uploader API
  uploader:
    build: .
    command: puma
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "9292:9292"
    links:
      - clamav-rest
  clamav:
     build: https://github.com/ministryofjustice/moj-clamav-daemon.git
  clamav-rest:
    build: https://github.com/ministryofjustice/moj-clamav-rest.git
    links:
      - clamav:clamav-server
    environment:
      HOST: clamav-server
      PORT: 3310
    depends_on:
      - clamav
    ports:
      - 8080:8080
